### ISSUE TITLE
push before creating a merge request

### ISSUE THREAD

**Issue by mathroc** [vishwanatharondekar/gitlab-cli#24] opened 2017-03-20 16:40 UTC
push the local branch before creating the merge request so that it works if we forgot (or are too lazy) to push it first

**Comment by vishwanatharondekar** [comment] 2017-03-22 16:03
This is almost duplicate of https://github.com/vishwanatharondekar/gitlab-cli/issues/9 which I want to do. 
Although, in this you are asking to make a push rather than telling user. Will want to check what hub does.

**Comment by vishwanatharondekar** [comment] 2017-11-04 14:14
Closing this as this is duplicate on #9 . Cleaning up issues.

**Closed by vishwanatharondekar** 2017-11-04 14:14 UTC
