### ISSUE TITLE
lab command just hanging on

### ISSUE THREAD

**Issue by andkirby** [vishwanatharondekar/gitlab-cli#55] opened 2017-12-06 07:26 UTC
I missed installation for global config and it's always hanging on. Yeah, it's some kinda minor issue, but seem you could make it more friendly.

Trying to run `lab` and `lab merge-request --help`:
```
0 kirby-pc 07:39:43 /d/home
✓ $ lab

130 kirby-pc 08:00:37 /d/home
✗ $ lab merge-request --help

130 kirby-pc 08:02:34 /d/home
✗ $
```

**Comment by vishwanatharondekar** [comment] 2017-12-06 10:02
You mean it returns without doing anything. Can you tell me exact steps to get this behaviour. We recently had major changes done, so this might be happening because of that.

**Comment by vishwanatharondekar** [comment] 2017-12-14 15:37
@andkirby please share the steps so I can try reproducing and fixing this.

**Comment by andkirby** [comment] 2017-12-15 13:06
@vishwanatharondekar I ran these command without setting GitLab token.
It was just hanging on connect to the server, I guess.
Hanging longer than 2 min, really confusing.

**Comment by vishwanatharondekar** [comment] 2017-12-15 13:37
@andkirby Can you confirm if it worked fine after setting the gitlab token. 

I will check the case of fresh install without setting any configs to reproduce this issue. Thanks for helping.

**Comment by vishwanatharondekar** [comment] 2018-01-07 08:03
I am not able to reproduce this. If you skip the token, it goes in loop asking for it. The hanging behaviour might be related to having all values (maybe wrong values) and then api request just waiting for getting timed out. I will fix this if I am able to reproduce this. Closing now.

**Closed by vishwanatharondekar** 2018-01-07 08:03 UTC
