### ISSUE TITLE
Error while creating MR

### ISSUE THREAD

**Issue by prabhay759** [vishwanatharondekar/gitlab-cli#58] opened 2018-05-31 13:36 UTC
Hello All,

I am getting below error while creating MR
Error occured :
 { Error: Command failed: git config branch.DisabledTest.remote
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'git config branch.DisabledTest.remote' }

**Comment by vishwanatharondekar** [comment] 2018-05-31 14:18
Duplicate of https://github.com/vishwanatharondekar/gitlab-cli/issues/57 . Please follow instructions there to resolve the issue.

**Closed by vishwanatharondekar** 2018-05-31 14:18 UTC

**Comment by prabhay759** [comment] 2018-06-01 05:40
Thank you @vishwanatharondekar It helps. But still, I am struggling with this issue while creating pull request. The error message is not helping.

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn 'C:/Program ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by vishwanatharondekar** [comment] 2018-06-01 08:56
Can you try using -m option for giving the message. I think utility is trying to open editor on the windows machine and its not set. 

```
lab merge-request -m "Merge request title here"
```

I will try to use this on windows machine see if I can reproduce the issue. Thanks for reporting.

**Comment by prabhay759** [comment] 2018-06-01 13:27
It worked with -m option thank you!
