### ISSUE TITLE
create mr with cli failed: 404 - {"status":"404","error":"Not Found"}

### ISSUE THREAD

**Issue by yongchao88** [vishwanatharondekar/gitlab-cli#92] opened 2020-04-29 07:50 UTC
I have already configured the gitlab url and gitlab token first.

# lab mr -b test -t develop -m 'merge this test branch to develop branch' -o
Couldn't create merge request
404 - {"status":"404","error":"Not Found"}

below is the verbose log detail:

# lab mr -b test -t develop -m 'merge this test branch to develop branch' -o -v
Verbose option used. Detailed logging information will be emitted.

Getting base branch information

Getting base branch name :
Argument provided : test
Base branch name obtained : test

Getting remote of branch : test
Executing git config branch.test.remote
Remote obtained : origin

Getting URL of remote : origin
Executing  git config remote.origin.url
URL of remote obtained : git@gitlab.xxxx-inc.xxxx/tools.git

gitlab host obtained : gitlab.xxx-inc.com

Project name derived from host : xxxx/tools

Getting gitlab project info for : xxx/tools
Base project info obtained : "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n    <script src=\"/home/js/jquery-1.11.3.min.js\"></script>\r\n    <script src=\"/home/js/jquery-adapter.js\"></script>\r\n    <script src=\"/home/js/common.js?11\"></script>\r\n    <script src=\"/home/js/xxxxx-face-login.js\"></script>\r\n</head>\r\n<body>\r\n<div id=\"_umfp\" style=\"width:0px;height:0px;overflow:hidden\">\r\n</div>\r\n<form method=\"post\" id=\"form\" action=\"\" >\r\n    <input type=\"hidden\" name=\"action\" value=\"PreLoginAction\" />\r\n\t<input type=\"hidden\" name=\"event_submit_do_PreLogin\" value=\"false\" />\r\n    <input type=\"hidden\" id=\"deviceIp\" name=\"deviceIp\"  value=\"\"/>\r\n    <input type=\"hidden\" id=\"trustEnvToken\" name=\"trustEnvToken\"  value=\"\"/>\r\n    <input type=\"hidden\" id=\"trustEnvTokenErrorInfo\" name=\"trustEnvTokenErrorInfo\"  value=\"\"/>\r\n    <input type=\"hidden\" name=\"caLoginKey\" value=\"\"/>\r\n    <input type=\"hidden\" name=\"umidTokenId\" value=\"xxxx\" >\r\n    <input type=\"hidden\" name=\"disableCert\" value=\"true\" >\r\n    <input type=\"hidden\" name=\"alipayFaceMetaInfo\" id=\"xxxyFaceMetaInfo\" value=\"\" >\r\n    \r\n</form>\r\n<script type=\"text/javascript\">\r\n    window.ssoConfig = {\r\n        '_sso_csrftoken_': 'xxxx',\r\n        'intranet': 'true',\r\n        'ipAddr': 'xxxxx',\r\n    }\r\n\r\n        try {\r\n        var metaInfo = getMetaInfo();\r\n        if (metaInfo != undefined) {\r\n            $('#alipayFaceMetaInfo').val(JSON.stringify(metaInfo));\r\n        }\r\n    } catch (e) {\r\n    }\r\n\r\n\r\ntry {\r\n        var getIpComplete = false;\r\n\tfunction onJSONPCallback(data) {\r\n\t\t$('#deviceIp').val(data.x_forwarded_for);\r\n        getIpComplete=true;\r\n\t}\r\n\tGetDeviceIp(\"https://xxx-xx.xxx-inc.com/ip.js\");\r\n\r\n    \tvar trustEnvToken = false;\r\n\tvar trustEnvTokenErrorInfo = {};\r\n    function tetCb(data) {\r\n        if (data && data.token) {\r\n            $('#trustEnvToken').val(data.token);\r\n            trustEnvToken=true;\r\n        } else {\r\n            trustEnvToken=false;\r\n            trustEnvTokenErrorInfo = {\"readyState\": 4, \"status\": 200, \"statusText\": \"token is blank\"};\r\n        }\r\n    }\r\n    var pageLoadTimestamp = new Date().getTime();\r\n\r\n    getTrustEnvToken('tetCb', 'xxxx-sso_001', 1, 'xxxxx', pageLoadTimestamp, trustEnvTokenErrorInfo);\r\n\r\n    var iIntervalId =setInterval(function(){\r\n        var currentTimestamp = new Date().getTime();\r\n        if((currentTimestamp-pageLoadTimestamp) > 600 || (getIpComplete && trustEnvToken)){\r\n            clearInterval(iIntervalId);\r\n            try {\r\n                if (!trustEnvTokenErrorInfo) {\r\n                    trustEnvTokenErrorInfo = {};\r\n                }\r\n\r\n                if (!trustEnvToken) {\r\n                    if (!trustEnvTokenErrorInfo.statusText) {\r\n                        trustEnvTokenErrorInfo.statusText = \"no response, maybe timeout\";\r\n                    }\r\n                }\r\n\r\n                trustEnvTokenErrorInfo.requestId = 'xxxxxxx';\r\n                trustEnvTokenErrorInfo.time = pageLoadTimestamp;\r\n                $(\"#trustEnvTokenErrorInfo\").val(JSON.stringify(trustEnvTokenErrorInfo));\r\n            } catch (e) {\r\n            }\r\n            // console.log(\"errorInfo=\" + JSON.stringify(trustEnvTokenErrorInfo))\r\n            document.getElementById('form').submit();\r\n        }\r\n    },50);\r\n} catch (e) {\r\n    document.getElementById('form').submit();\r\n}\r\n\r\n</script> \r\n</body>\r\n</html>\r\n<script>\r\n    (function (w, d, t) {\r\n        var s = d.createElement(t), m = d.getElementsByTagName(t)[0];\r\n        s.async = 1;\r\n        s.src = \"https://g.xxxx.com/sd/pointman/js/pt2.js?_=\" + Math.floor((new Date()).getTime() / 36e5);\r\n        m.parentNode.insertBefore(s, m);\r\n\r\n        w._pointman_q = w._pointman_q || [];\r\n        _pointman_q.push([\"um\", function (umx) {\r\n            var container = document.getElementById(\"_umfp\");\r\n            umx.init({\r\n                timeout: 3000,\r\n                userId: '',\r\n                token: 'xxxx',\r\n                userFieldId: 'loginAccountInput',\r\n                serviceLocation: \"cn\",\r\n                appName: 'buc',\r\n                model: 'L1',\r\n                containers: {flash: container, dcp: container}\r\n            });\r\n        }]);\r\n    })(window, document, \"script\");\r\n</script>"

Getting target branch information
Remote branch name obtained : develop

Getting remote of branch : develop
Executing git config branch.develop.remote
Remote obtained : origin

Getting URL of remote : origin
Executing  git config remote.origin.url
URL of remote obtained : git@gitlab.xxxx-inc.xxxx/tools.git

Getting target project information
Target project info obtained : "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n    <script src=\"/home/js/jquery-1.11.3.min.js\"></script>\r\n    <script src=\"/home/js/jquery-adapter.js\"></script>\r\n    <script src=\"/home/js/common.js?11\"></script>\r\n    <script src=\"/home/js/xxx-face-login.js\"></script>\r\n</head>\r\n<body>\r\n<div id=\"_umfp\" style=\"width:0px;height:0px;overflow:hidden\">\r\n</div>\r\n<form method=\"post\" id=\"form\" action=\"\" >\r\n    <input type=\"hidden\" name=\"action\" value=\"PreLoginAction\" />\r\n\t<input type=\"hidden\" name=\"event_submit_do_PreLogin\" value=\"false\" />\r\n    <input type=\"hidden\" id=\"deviceIp\" name=\"deviceIp\"  value=\"\"/>\r\n    <input type=\"hidden\" id=\"trustEnvToken\" name=\"trustEnvToken\"  value=\"\"/>\r\n    <input type=\"hidden\" id=\"trustEnvTokenErrorInfo\" name=\"trustEnvTokenErrorInfo\"  value=\"\"/>\r\n    <input type=\"hidden\" name=\"caLoginKey\" value=\"\"/>\r\n    <input type=\"hidden\" name=\"umidTokenId\" value=\"xxxxx\" >\r\n    <input type=\"hidden\" name=\"disableCert\" value=\"true\" >\r\n    <input type=\"hidden\" name=\"alipayFaceMetaInfo\" id=\"alipayFaceMetaInfo\" value=\"\" >\r\n    \r\n</form>\r\n<script type=\"text/javascript\">\r\n    window.ssoConfig = {\r\n        '_sso_csrftoken_': 'xxxxx',\r\n        'intranet': 'true',\r\n        'ipAddr': 'xxxxx',\r\n    }\r\n\r\n        try {\r\n        var metaInfo = getMetaInfo();\r\n        if (metaInfo != undefined) {\r\n            $('#alipayFaceMetaInfo').val(JSON.stringify(metaInfo));\r\n        }\r\n    } catch (e) {\r\n    }\r\n\r\n\r\ntry {\r\n        var getIpComplete = false;\r\n\tfunction onJSONPCallback(data) {\r\n\t\t$('#deviceIp').val(data.x_forwarded_for);\r\n        getIpComplete=true;\r\n\t}\r\n\tGetDeviceIp(\"https://xxx-office.xxxx-inc.com/ip.js\");\r\n\r\n    \tvar trustEnvToken = false;\r\n\tvar trustEnvTokenErrorInfo = {};\r\n    function tetCb(data) {\r\n        if (data && data.token) {\r\n            $('#trustEnvToken').val(data.token);\r\n            trustEnvToken=true;\r\n        } else {\r\n            trustEnvToken=false;\r\n            trustEnvTokenErrorInfo = {\"readyState\": 4, \"status\": 200, \"statusText\": \"token is blank\"};\r\n        }\r\n    }\r\n    var pageLoadTimestamp = new Date().getTime();\r\n\r\n    getTrustEnvToken('tetCb', 'xxx-sso_001', 1, 'xxxxxx', pageLoadTimestamp, trustEnvTokenErrorInfo);\r\n\r\n    var iIntervalId =setInterval(function(){\r\n        var currentTimestamp = new Date().getTime();\r\n        if((currentTimestamp-pageLoadTimestamp) > 600 || (getIpComplete && trustEnvToken)){\r\n            clearInterval(iIntervalId);\r\n            try {\r\n                if (!trustEnvTokenErrorInfo) {\r\n                    trustEnvTokenErrorInfo = {};\r\n                }\r\n\r\n                if (!trustEnvToken) {\r\n                    if (!trustEnvTokenErrorInfo.statusText) {\r\n                        trustEnvTokenErrorInfo.statusText = \"no response, maybe timeout\";\r\n                    }\r\n                }\r\n\r\n                trustEnvTokenErrorInfo.requestId = 'xxxxxx';\r\n                trustEnvTokenErrorInfo.time = pageLoadTimestamp;\r\n                $(\"#trustEnvTokenErrorInfo\").val(JSON.stringify(trustEnvTokenErrorInfo));\r\n            } catch (e) {\r\n            }\r\n            // console.log(\"errorInfo=\" + JSON.stringify(trustEnvTokenErrorInfo))\r\n            document.getElementById('form').submit();\r\n        }\r\n    },50);\r\n} catch (e) {\r\n    document.getElementById('form').submit();\r\n}\r\n\r\n</script> \r\n</body>\r\n</html>\r\n<script>\r\n    (function (w, d, t) {\r\n        var s = d.createElement(t), m = d.getElementsByTagName(t)[0];\r\n        s.async = 1;\r\n        s.src = \"https://g.xxx.com/sd/pointman/js/pt2.js?_=\" + Math.floor((new Date()).getTime() / 36e5);\r\n        m.parentNode.insertBefore(s, m);\r\n\r\n        w._pointman_q = w._pointman_q || [];\r\n        _pointman_q.push([\"um\", function (umx) {\r\n            var container = document.getElementById(\"_umfp\");\r\n            umx.init({\r\n                timeout: 3000,\r\n                userId: '',\r\n                token: 'xxxx',\r\n                userFieldId: 'loginAccountInput',\r\n                serviceLocation: \"cn\",\r\n                appName: 'buc',\r\n                model: 'L1',\r\n                containers: {flash: container, dcp: container}\r\n            });\r\n        }]);\r\n    })(window, document, \"script\");\r\n</script>"

Getting merge request title. Argument provided : merge this test branch to develop branch
Title obtained with -m option: merge this test branch to develop branch
Merge request title : merge this test branch to develop branch

Creating merge request
Couldn't create merge request
404 - {"status":"404","error":"Not Found"}

**Comment by vishwanatharondekar** [comment] 2020-04-29 08:23
Looks like project does not exist on gitlab or token doesn't have access to it. Getting project information failed. 

Can you please check if you are able to create gitlab merge request using UI.

**Comment by plumhly** [comment] 2020-05-16 17:25
I also encountered this 404 error. The reason I got the error is that the show method passed in `path_with_namespace` instead of `project_id`.

gitlab's api, the parameter has `id`, it will have this problem if it is used `path_with_namespace` instead of `project_id `. 

I changed the process, first parse out `projectName` (like game not ios/game), and then call the `search` method to get the `project_id`.


I don't know why path_with_namespace will return 404 and project_id not?

**Comment by vishwanatharondekar** [comment] 2020-05-17 05:17
I checked this on gitlab.com and couldnt reproduce error. 

@yongchao88 @plumhly What is the gitlab version you are using. You can check your gitlab version at https://your.domain.name/help

**Comment by plumhly** [comment] 2020-05-17 05:26
@vishwanatharondekar 
gitlab version: GitLab Community Edition 11.7.3

**Comment by vishwanatharondekar** [comment] 2020-05-17 05:46
I checked gitlab api once again to be sure https://docs.gitlab.com/ee/api/projects.html#get-single-project It does support getting the project by name rather than using id. Are there any special characters in your project name which need encoding?

**Comment by plumhly** [comment] 2020-05-17 06:35
My path is `ios/woof-app`, and i urlEncode the path. I know `id` parameter can use number and string. Can you attach your url?

**Comment by vishwanatharondekar** [comment] 2020-05-17 06:48
I was doing it on https://gitlab.com/vishwanatharondekar/test. is ios/woof-app the full path including. Is your org name ios ?

**Comment by plumhly** [comment] 2020-05-17 07:00
I don't know what `NAMESPACE/PROJECT_PATH`is. `ios/woof-app` is my repository name, It is also a parameter of the `gitlab.Project.show` method in your code.

**Comment by Lord-Y** [comment] 2020-07-28 14:54
@vishwanatharondekar I have the same problem and my gitlab version is 12.9.2.
When I try to do a merge request, it end up with:

`Couldn't create merge request
404 - "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL was not found on this server.</p>\n</body></html>\n"`

I installed gitlab cli from npm to make dig and it sounds like @plumhly is true. So based on the cli, you must not do directly a `gitlab.Projects.show(projectName)` but a search before with the projectName in order to get the id.
I hardcoded my gitlab project id and I was able to successfully create my merge request.

**Comment by vishwanatharondekar** [comment] 2020-08-25 05:11
Fixed with https://github.com/vishwanatharondekar/gitlab-cli/pull/108

**Closed by vishwanatharondekar** 2020-08-25 05:11 UTC

**Comment by vishwanatharondekar** [comment] 2020-08-25 06:42
Published as 2.0.9
